# Generated by Django 5.1.2 on 2024-10-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=20)),
                ("surname", models.CharField(max_length=20)),
                ("student_id", models.IntegerField(unique=True)),
                ("course", models.CharField(max_length=20)),
            ],
        ),
    ]
